name:                league-client
version:             0.1.0.0
github:              "moreal/league-client"
license:             BSD3
author:              "Lee Dogeon"
maintainer:          "dev.moreal@gmail.com"
copyright:           "Lee Dogeon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            LeagueOfLegends

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/moreal/league-client#readme>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  league-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - league-client

tests:
  league-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - league-client
    - hspec >= 2.7.10 && < 3
    - hspec-discover
